name = "BatteryPeck"
uuid = "e9eeebe6-cbd9-464a-ae64-628cb336b211"
authors = ["Koen Linders <k.s.j.linders@tudelft.nl>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"

[compat]
DifferentialEquations = "7"
ModelingToolkit = "10"
ModelingToolkitStandardLibrary = "2"
